# Generated by Django 3.1.7 on 2021-03-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20210326_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variável', 'verbose_name_plural': 'Variações'},
        ),
    ]
