# Generated by Django 3.1.7 on 2021-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quant_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
